version: '3.8'

services:
  database:
    container_name: database
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/laravel
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
volumes:
  db:
    driver: local